# Uncomment this line to define a global platform for your project
platform :ios, '15.5'

use_frameworks!
use_modular_headers!

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_application_path = '../'
  eval(File.read(File.join(flutter_application_path, '.flutter-plugins-dependencies')))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
