platform :ios, '15.5'

use_frameworks!
use_modular_headers!

# Path to Flutter application
flutter_application_path = File.expand_path('..', __dir__)
require File.join(flutter_application_path, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

target 'Runner' do
  flutter_ios_podfile_setup
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
    end
  end
end
